// Code generated by "stringer -type=StatusCode"; DO NOT EDIT.

package http

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ok-200]
	_ = x[Created-201]
	_ = x[Accepted-202]
	_ = x[MultipleChoice-300]
	_ = x[MovedPermanently-301]
	_ = x[Found-302]
	_ = x[BadRequest-400]
	_ = x[Unauthorized-401]
	_ = x[PaymentRequired-402]
}

const (
	_StatusCode_name_0 = "OkCreatedAccepted"
	_StatusCode_name_1 = "MultipleChoiceMovedPermanentlyFound"
	_StatusCode_name_2 = "BadRequestUnauthorizedPaymentRequired"
)

var (
	_StatusCode_index_0 = [...]uint8{0, 2, 9, 17}
	_StatusCode_index_1 = [...]uint8{0, 14, 30, 35}
	_StatusCode_index_2 = [...]uint8{0, 10, 22, 37}
)

func (i StatusCode) String() string {
	switch {
	case 200 <= i && i <= 202:
		i -= 200
		return _StatusCode_name_0[_StatusCode_index_0[i]:_StatusCode_index_0[i+1]]
	case 300 <= i && i <= 302:
		i -= 300
		return _StatusCode_name_1[_StatusCode_index_1[i]:_StatusCode_index_1[i+1]]
	case 400 <= i && i <= 402:
		i -= 400
		return _StatusCode_name_2[_StatusCode_index_2[i]:_StatusCode_index_2[i+1]]
	default:
		return "StatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
